### PR TITLE
merge READMEs

### PR DESCRIPTION
**Pull request by capalmer85**

### CODE REVIEW

**Comment by capalmer85** [comment]
@plujan I added a bunch of blank lines for formatting and basically added your instructions as a new section (with a few very minor revisions).

**Comment by capalmer85** [comment]
BTW, I believe that bestlumi.py is not in this repo and that it is used just to get a normtag json file where there is data.   makeValidNT.py has the same functionality and is in the repo.  Could you consider using it?  I think it would be as simple as replacing this line in makeJSON.sh:
https://github.com/CMS-LUMI-POG/Normtags/blob/master/makeJSON.sh#L13
with something like
python makeValidNT.py -i output.csv -o normtag_${i}.json -n ${i}

**Review by plujan — APPROVED** [review]

**Comment by plujan** [comment]
@capalmer85: I tried the simple substitution but this produces a few errors (also the way I operate it's better to have the JSON output to the screen). I'll come back to this later when I have a bit more time, since it would be nice to have them merged. Really it would make the most sense to eliminate a manual step and add the output directly to the JSON file (of course it would still need to be manually edited if sections need to be invalidated, but since the vast majority of fills don't need this step, it would save a lot of work).

**Comment by capalmer85** [comment]
@plujan OK.  I just want to make sure though.  The json file is a normtag json file, right?  (As opposed to a data certification, AKA golden json, json file.)

**Comment by plujan** [comment]
Yep, that's correct.

**Pull request merged**
