### PR TITLE
Update pccnt rmmost5267

### PR DESCRIPTION
**Pull request by capalmer85**
Updated pcc normtag to remove bad runs from 5267. @jsalfeld @DavidSticklandCMS @plujan 

Please review and merge/comment.  Thanks.

### CODE REVIEW

**Comment by capalmer85** [comment]
Sorry I changed pre2 to pre6 and that confused git's diff program.  I removed these lines from 5267:

["pccLUM17001pre2",{"279846":[[2, 34]]}],
["pccLUM17001pre2",{"279848":[[1, 80]]}],
["pccLUM17001pre2",{"279849":[[1, 281]]}],
["pccLUM17001pre2",{"279850":[[1, 5]]}],
["pccLUM17001pre2",{"279851":[[1, 10]]}],
["pccLUM17001pre2",{"279852":[[1, 29]]}],
["pccLUM17001pre2",{"279853":[[1, 18]]}],
["pccLUM17001pre2",{"279854":[[1, 6]]}],
["pccLUM17001pre2",{"279855":[[1, 4]]}],
["pccLUM17001pre2",{"279856":[[1, 5]]}],
["pccLUM17001pre2",{"279857":[[1, 4]]}],
["pccLUM17001pre2",{"279858":[[1, 10]]}],
["pccLUM17001pre2",{"279859":[[1, 4]]}],
["pccLUM17001pre2",{"279860":[[1, 3]]}],
["pccLUM17001pre2",{"279861":[[1, 6]]}],
["pccLUM17001pre2",{"279864":[[5, 12]]}],
["pccLUM17001pre2",{"279865":[[3, 148]]}],


and I added this one for fill 5412:
["pccLUM17001pre6",{"283171":[[50, 118], [121, 332], [334, 534], [537, 542]]}],

**Comment by plujan** [comment]
These changes look fine to me.

**Comment by capalmer85** [comment]
@jingyuluo can you merge this and then make another PR removing in the LSs that @jsalfeld mentioned you have filtered in your version?

**Comment by jingyuluo** [comment]
@capalmer85 Yes, I'll merge this and make another PR

**Pull request merged**
