### PR TITLE
Added run 277933.

### PR DESCRIPTION
**Pull request by samborsol**
Best lumi was originally PLT, but the PLT is noisy compared to both HF and BCM1F, normtag updated so HF is best lumi.

### CODE REVIEW

**Comment by capalmer85** [comment]
@samborsol can you change to hfoc16v3**c**?  Also put the link to the plot (from the lumipro area) in this thread please.

**Comment by capalmer85** [comment]
@samborsol  You don't need to make another PR.  You should just push to the same branch again with the new updates:

git push samsgit update-datacertNT-20160804_v2

Also, I wanted you to change ALL of the hfoc16v3b to hfoc16v3c.

**Comment by samborsol** [comment]
I apologize for this, Chris, but I think I have messed up my git setup,
because I cannot get the branch update-datacertNT-20160804_v2 to pull.

**Comment by samborsol** [comment]
Chris,
Here is what happens,

git add normtag_DATACERT.json

git commit -m "trying to update"
[master 6c3926a] trying to update
 1 file changed, 8 insertions(+), 7 deletions(-)

git push samborsol update-datacertNT-20160804_v2
To https://github.com/samborsol/Normtags/
! [rejected]        update-datacertNT-20160804_v2 ->
update-datacertNT-20160804_v2 (fetch first)
error: failed to push some refs to 'https://github.com/samborsol/Normtags/'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first merge the remote changes (e.g.,
hint: 'git pull') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by samborsol** [comment]
Hello Chris,
I think I resolved things to the correct branch.
Cheers,
Samuel

**Pull request closed without merging**
