### PR TITLE
update a typo and add lots of pcc

### PR DESCRIPTION
**Pull request by capalmer85**
@jsalfeld has checked so I will merge

### CODE REVIEW

**Comment by jsalfeld** [comment]
yes, this will then appear for the collaboration right?

**Comment by capalmer85** [comment]
after we pull it in the lumipro area

**Comment by jsalfeld** [comment]
yes but a cronjob is doing that no?

**Comment by capalmer85** [comment]
unfortunately the git pull doesn't work from the cronjob yet.

**Comment by jsalfeld** [comment]
ok pull on lumipro worked, no differences

**Pull request merged**
