### PR TITLE
Normtagsv1

### PR DESCRIPTION
**Pull request by thapakrish**

### CODE REVIEW

**Comment by capalmer85** [comment]
@thapakrish these instructions looks very nice.  It is ok to merge.  @DavidSticklandCMS can you git clone this package and give it a try after I merge?

**Comment by capalmer85** [comment]
@thapakrish  Oh.... hang on.  What is lumiValidate.py?  Can you push that too?  It is not here and a user won't know where to get it.

**Comment by thapakrish** [comment]
@capalmer85 done! instead of pushing the code, I added a line to copy it from ~cmsbril/public. This script might be improved in the future (by Jonas) and we'd like to have the improved plots also.

**Comment by DavidSticklandCMS** [comment]
Can someone tell me exactly how to get these instructions please?
On 25 Apr 2016, at 17:26, capalmer85 <notifications@github.com<mailto:notifications@github.com>> wrote:

@thapakrishhttps://github.com/thapakrish these instructions looks very nice. It is ok to merge. @DavidSticklandCMShttps://github.com/DavidSticklandCMS can you git clone this package and give it a try after I merge?

**Comment by capalmer85** [comment]
Go to https://github.com/CMS-LUMI-POG/Normtags.  They are at the
bottom of the page.  You can also find them in the README.md file.

**Comment by capalmer85** [comment]
More specifically the bottom of the page:
https://github.com/CMS-LUMI-POG/Normtags#instructions-for-producing-normtags-per-lumi-section

**Pull request merged**
